# HW6, Practice Working with Projects

## 1. Extending arthritis_proj_demo

### i. Create your own branch

If you have not done so yet, clone https://github.com/team-mayes/arthritis_proj_demo. If you have, do a `git pull` to make sure you have the latest version of this project.

Make a new branch on which you will develop a new feature.

### ii. Add some functionality to the project

For example, extend `data_proc.py` by allowing it to handle different numbers of data points per patient.

### iii. Write tests for your new functionality

`data_proc.py` should have at least 90% coverage.

## 2. Working with NumPy Arrays

i. Create the matrix $$ a = \left( \begin{array}{cccc}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12\\
13 & 14 & 15 & 16\end{array} \right) $$

In [1]:
import numpy as np

In [8]:
a = np.arange(1,17)
a = a.reshape((4,4))

ii. From $a$, define the submatrix
$$ b = \left( \begin{array}{cc}
6 & 7 & \\
10 & 11 \end{array} \right) $$

In [14]:
b = a[1:3,1:3]

In [15]:
b

array([[ 6,  7],
       [10, 11]])

iii. Create a NumPy array $c$ of all zeros that is 3 x 2, and an array $d$ of all ones that is 2 x 3. 

In [18]:
c = np.zeros((3,2))
d = np.ones((2,3))
print(c)
print(d)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


iv. Join $c$ and $d$ into one 3x4 array, transforming $d$ as necessary.

In [20]:
np.hstack([c,d.T])

array([[ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  1.,  1.]])

v. Join $c$ and $d$ into one 6x2 array, transforming $d$ as necessary.

In [21]:
np.vstack([c,d.T])

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])