# HW7, Practice with NumPy and Linear Algebra

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 1. Probability fundamentals

### i. There are 27 students in the class. Assuming that everyone turns in a project, and I grade them in random order, how many ways (orders) can I evaluate the projects?

In [2]:
np.math.factorial(27)

10888869450418352160768000000

## 2. Matrices and Linear Algebra

### i. Find **C**

$$ \mathbf{AB} = \left[ \begin{array}{cc}
4 & 3 \\
7 & 2 \end{array} \right] \left[ \begin{array}{cc}
2 & 5 \\
1 & 6 \end{array} \right] = \mathbf{C}$$

In [3]:
np.matmul(
    np.array([[4,3],[7,2]]),
    np.array([[2,5],[1,6]]))

array([[11, 38],
       [16, 47]])

### ii. Find **F**

$$ \mathbf{DE} = \left[ \begin{array}{cc}
3 & 6 & 1 \end{array} \right] \left[ \begin{array}{cc}
1 \\
2 \\
4 \end{array} \right] = \mathbf{F}$$

In [5]:
print(np.matmul(
    np.array([3,6,1]),
    np.array([1,2,4])))
print(np.dot(
    np.array([3,6,1]),
    np.array([1,2,4])))

19
19


### iii. Find det **G** Given:

$$ \mathbf{G} = \left[ \begin{array}{ccc}
-1 & 1 & 2 \\
3 & -1 & 1 \\
-1 & 3 & 4\end{array} \right]$$

In [9]:
G = np.array([
    [-1,1,2],
    [3,-1,1],
    [-1,3,4]])
np.linalg.det(G)

10.000000000000002

### iv. Find $\mathbf{G}^{-1}$ (G given above)

In [10]:
np.linalg.inv(G)

array([[-0.7,  0.2,  0.3],
       [-1.3, -0.2,  0.7],
       [ 0.8,  0.2, -0.2]])

### v. Check that your answer to the previous question part is correct

### vi. Solve the following linear system of equations. Then check your work.

$$  \begin{array}{ccc}
6x_0 &+& 4x_1 &=&  2 \\
3x_0 &-& 5x_1 &=& -34 \end{array} $$

In [11]:
A = np.array([
    [6, 4],
    [3, -5]
])
b = np.array([2,-34])
np.linalg.solve(A,b)

array([-3.,  5.])

### vii. Find the eigenvalues and associated eigenvectors of the matrix below. Then check your answers.

$$ \mathbf{H} = \left[ \begin{array}{cc}
-5 & 2 \\
2 & 2\end{array} \right]$$

In [13]:
H = np.array([
    [-5,2],
    [2,2]
])
eigs, vecs = np.linalg.eig(H)
for eig, vec in zip(eigs, vecs):
    print("Eigenvalue {}".format(eig))    
    print("goes along with eigenvector ")
    print(vec)
    print("\n")

Eigenvalue -5.531128874149275
goes along with eigenvector 
[-0.96649965 -0.25666794]


Eigenvalue 2.531128874149275
goes along with eigenvector 
[ 0.25666794 -0.96649965]





## 1. Pandas

i. Create a Pandas dataframe with the following data collected from 5 samples of the species Iris setosa:

|sample_label | sepal_length | sepal_width | petal_length | petal_width |
|-----------|-----------|-----------|-----------|-----------|
| a | 5.1 | 3.5 | 1.4 | 0.2 |
| b | 4.9 | 3.0 | 1.4 | 0.2 |
| c | 4.7 | 3.2 | 1.3 | 0.2 |
| d | 4.6 | 3.1 | 1.5 | 0.2 |
| e | 5.0 | 3.6 | 1.4 | 0.2 |

Also name the dataframe "iris_setosa" and the indices "sample_label".

In [18]:
irises = pd.DataFrame(data = np.array([
    [5.1, 3.5, 1.4, 0.2],
    [4.9, 3.0, 1.4, 0.2],
    [4.7, 3.2, 1.3, 0.2],
    [4.6, 3.1, 1.5, 0.2],
    [5.0, 3.6, 1.4, 0.2]
]), columns=['sepal_length','sepal_width','petal_length','petal_width'],
                     index=list('abcde'))

irises.index.name = 'sample_label'
irises.name = 'iris_setosa'
irises

sepal_length  sepal_width  petal_length  petal_width
sample_label                                                      
a                      5.1          3.5           1.4          0.2
b                      4.9          3.0           1.4          0.2
c                      4.7          3.2           1.3          0.2
d                      4.6          3.1           1.5          0.2
e                      5.0          3.6           1.4          0.2

ii. Display only the data for sepal dimensions.

In [19]:
irises[['sepal_length','sepal_width']]

sepal_length  sepal_width
sample_label                           
a                      5.1          3.5
b                      4.9          3.0
c                      4.7          3.2
d                      4.6          3.1
e                      5.0          3.6

iii. Display only the data for sample "c".

In [24]:
irises.loc['c']

sepal_length    4.7
sepal_width     3.2
petal_length    1.3
petal_width     0.2
Name: c, dtype: float64